# Configuration for hitters_model
model_name: hitters_model_baseline
embedding_dim: 64
batch_size: 128
learning_rate: 0.001
epochs: 50
save_path: ./models/hitters_model_baseline.pt
train_range: 2005-2014
