# Name: Cold Start Model Configuration
model_name: cold_start
model_dir: cold_start/
#Dataset information 
year: 2024
start_week: 12
end_week: 44

# Number of different embeddings needed
num_players: 41908
num_pitch_types: 21
num_prior_outcomes: 4
num_zones: 14

# Embedding Dimensions
pitcher_embed_dim: 64
batter_embed_dim: 24
catcher_embed_dim: 16
runner_embed_dim: 8
zones_embed_dim: 6
prior_pitch_type_embed_dim: 6
prior_outcome_embed_dim: 4

#Categorical Dimensions
# Balls, Strikes, Outs, Score, Inning, Half, At Bat, Pitch number, Pitcher handedness, Batter handedness
remaining_dims: 10

# Model Hyperparameters
hidden_size: 128
num_layers: 2
lr: 0.001
mask_value: 3.5
lambda_entropy: 0.001
temperature: 1.25
batch_size: 1

weight_path: pitch_type_model/cold_start/checkpoints/cold_start_2023.pt